In [ ]:
import numpy as np
import time
INF=9999
v=int(input("Enter no. of vertices :"))
arr=np.random.randint(10,40,size=(v,v),dtype='int')
print(arr)
l=int(input("Enter the limit of time: "))
selected_node = [0,0,0,0,0]
cities={0:"Nagpur",1:"Pune",2:"Mumbai",3:"Bangalore",4:"HYderabad"}

edge = 0

selected_node[0] = True

start=time.perf_counter()
print("City : Time")
while (edge < v - 1):

    minimum = INF
    a = 0
    b = 0
    for m in range(v):
        if selected_node[m]:
            for n in range(v):
                if ((not selected_node[n]) and arr[m][n]):

                    if minimum > arr[m][n]:
                        minimum = arr[m][n]
                        a = m
                        b = n

    print(str(cities.get(a)) + "-" + str(cities.get(b)) + ":" + str(arr[a][b]))
    if (l>=arr[a][b]):
        print("********************************possible**************************************")
    selected_node[b] = True
    edge += 1
end=time.perf_counter()
print("The time taken is ",end-start)

Enter no. of vertices :5
[[25 13 22 14 32]
 [10 14 29 21 36]
 [23 36 10 14 12]
 [38 35 19 12 25]
 [22 23 29 35 12]]
Enter the limit of time: 18
City : Time
Nagpur-Pune:13
********************************possible**************************************
Nagpur-Bangalore:14
********************************possible**************************************
Bangalore-Mumbai:19
Mumbai-HYderabad:12
********************************possible**************************************
The time taken is  0.0004859000000578817


In [ ]:
import numpy as np
import time
INF=9999
v=int(input("Enter no. of vertices :"))
arr=np.random.randint(10,40,size=(v,v),dtype='int')
print(arr)
l=int(input("Enter the limit of time: "))
selected_node = [0,0,0,0,0,0]
cities={0:"Nagpur",1:"Pune",2:"Mumbai",3:"Bangalore",4:"HYderabad",5:"Agra"}

edge = 0

selected_node[0] = True

start=time.perf_counter()
print("City : Time")
while (edge < v - 1):

    minimum = INF
    a = 0
    b = 0
    for m in range(v):
        if selected_node[m]:
            for n in range(v):
                if ((not selected_node[n]) and arr[m][n]):

                    if minimum > arr[m][n]:
                        minimum = arr[m][n]
                        a = m
                        b = n

    print(str(cities.get(a)) + "-" + str(cities.get(b)) + ":" + str(arr[a][b]))
    if (l>=arr[a][b]):
        print("********************************possible**************************************")
    selected_node[b] = True
    edge += 1
end=time.perf_counter()
print("The time taken is ",end-start)

Enter no. of vertices :6
[[10 15 14 39 37 14]
 [23 39 33 20 32 11]
 [20 23 22 14 21 38]
 [36 22 12 30 15 29]
 [32 22 12 31 23 12]
 [22 12 14 19 10 26]]
Enter the limit of time: 23
City : Time
Nagpur-Mumbai:14
********************************possible**************************************
Nagpur-Agra:14
********************************possible**************************************
Agra-HYderabad:10
********************************possible**************************************
Agra-Pune:12
********************************possible**************************************
Mumbai-Bangalore:14
********************************possible**************************************
The time taken is  0.0003438999997342762


In [ ]:
import numpy as np
import time
INF=9999
v=int(input("Enter no. of vertices :"))
arr=np.random.randint(10,40,size=(v,v),dtype='int')
print(arr)
l=int(input("Enter the limit of time: "))
selected_node = [0,0,0,0,0]
cities={0:"Nagpur",1:"Pune",2:"Mumbai"}

edge = 0

selected_node[0] = True

start=time.perf_counter()
print("City : Time")
while (edge < v - 1):

    minimum = INF
    a = 0
    b = 0
    for m in range(v):
        if selected_node[m]:
            for n in range(v):
                if ((not selected_node[n]) and arr[m][n]):

                    if minimum > arr[m][n]:
                        minimum = arr[m][n]
                        a = m
                        b = n

    print(str(cities.get(a)) + "-" + str(cities.get(b)) + ":" + str(arr[a][b]))
    if (l>=arr[a][b]):
        print("********************************possible**************************************")
    selected_node[b] = True
    edge += 1
end=time.perf_counter()
print("The time taken is ",end-start)

Enter no. of vertices :4
[[21 33 31 21]
 [35 22 33 14]
 [23 27 22 20]
 [19 32 37 30]]
Enter the limit of time: 21
City : Time
Nagpur-None:21
********************************possible**************************************
Nagpur-Mumbai:31
Mumbai-Pune:27
The time taken is  0.00039759999981470173


In [ ]:
import numpy as np
import time
INF=9999
v=int(input("Enter no. of vertices :"))
arr=np.random.randint(10,40,size=(v,v),dtype='int')
print(arr)
l=int(input("Enter the limit of time: "))
selected_node = [0,0,0,0,0]
cities={0:"Nagpur",1:"Pune",2:"Mumbai",3:"Bangalore"}

edge = 0

selected_node[0] = True

start=time.perf_counter()
print("City : Time")
while (edge < v - 1):

    minimum = INF
    a = 0
    b = 0
    for m in range(v):
        if selected_node[m]:
            for n in range(v):
                if ((not selected_node[n]) and arr[m][n]):

                    if minimum > arr[m][n]:
                        minimum = arr[m][n]
                        a = m
                        b = n

    print(str(cities.get(a)) + "-" + str(cities.get(b)) + ":" + str(arr[a][b]))
    if (l>=arr[a][b]):
        print("********************************possible**************************************")
    selected_node[b] = True
    edge += 1
end=time.perf_counter()
print("The time taken is ",end-start)

Enter no. of vertices :3
[[36 31 17]
 [37 27 37]
 [21 30 27]]
Enter the limit of time: 12
City : Time
Nagpur-Mumbai:17
Mumbai-Pune:30
The time taken is  0.00036210000007486087
